
hide-cursor-when-typing = true

theme = "gruvbox"

[fonts]
family = "JetBrains Mono"
size = 19

[navigation]
mode = "BottomTab"
clickable = true
hide-if-single = false
use-current-path = true
color-automation = []

# [renderer]
# filters = ["newpixiecrt"]
